---
title: "K-Means"
author: "Sudisha Goswami"
date: "2025-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Performing K-Means on a Dataset with Plotting:

```{r pressure, echo=TRUE, message=TRUE, warning=TRUE, paged.print=TRUE}

# Set a random seed for reproducibility
set.seed(2)

# Generate a 50x2 matrix of random normal data
x <- matrix(rnorm(50 * 2), ncol = 2)

# Shift the first 25 points to create a distinct cluster
x[1:25, 1] <- x[1:25, 1] + 3
x[1:25, 2] <- x[1:25, 2] - 4

# Perform K-means clustering with 2 clusters and 20 random starts
km.out <- kmeans(x, 2, nstart = 20)

# Print the cluster assignments
km.out$cluster

# Set up a 1x2 plotting layout
par(mfrow = c(1, 2))

# Plot the data with points colored by their assigned cluster for K=2
plot(x, col = (km.out$cluster + 1),
main = "K-Means Clustering with K = 2",
xlab = "", ylab = "", pch = 20, cex = 2)

# Set a new random seed for the next part
set.seed(4)

# Perform K-means clustering with 3 clusters and 20 random starts
km.out <- kmeans(x, 3, nstart = 20)

# Print the full K-means output for K=3
km.out

# Plot the data with points colored by their assigned cluster for K=3
plot(x, col = (km.out$cluster + 1),
main = "K-Means Clustering with K = 3",
xlab = "", ylab = "", pch = 20, cex = 2)

# Set a new random seed for the next part
set.seed(4)

# Perform K-means with 3 clusters and only 1 random start
km.out <- kmeans(x, 3, nstart = 1)

# Print the total within-cluster sum of squares for 1 start
km.out$tot.withinss

# Perform K-means with 3 clusters and 20 random starts
km.out <- kmeans(x, 3, nstart = 20)

# Print the total within-cluster sum of squares for 20 starts
km.out$tot.withinss


```

## Thank You